version: "3.9"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.2
    container_name: es01-vector-experiment
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - http.host=0.0.0.0
    volumes:
      - ./elastic/es01/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-network
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.2
    container_name: kibana-vector-experiment
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - es01

networks:
  es-network:
    driver: bridge
